// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $admin_new from "./routes/admin/new.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_posts from "./routes/api/posts.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AdminEditor from "./islands/AdminEditor.tsx";
import * as $BackgroundMusic from "./islands/BackgroundMusic.tsx";
import * as $Carousel3D from "./islands/Carousel3D.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DropdownShowcase from "./islands/DropdownShowcase.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $HeroInteractive from "./islands/HeroInteractive.tsx";
import * as $RecepcionistaSiqueira from "./islands/RecepcionistaSiqueira.tsx";
import * as $SoundEffects from "./islands/SoundEffects.tsx";
import * as $TimelineParallax from "./islands/TimelineParallax.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/admin/new.tsx": $admin_new,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/posts.ts": $api_posts,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AdminEditor.tsx": $AdminEditor,
    "./islands/BackgroundMusic.tsx": $BackgroundMusic,
    "./islands/Carousel3D.tsx": $Carousel3D,
    "./islands/Counter.tsx": $Counter,
    "./islands/DropdownShowcase.tsx": $DropdownShowcase,
    "./islands/Header.tsx": $Header,
    "./islands/HeroInteractive.tsx": $HeroInteractive,
    "./islands/RecepcionistaSiqueira.tsx": $RecepcionistaSiqueira,
    "./islands/SoundEffects.tsx": $SoundEffects,
    "./islands/TimelineParallax.tsx": $TimelineParallax,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
